./install.sh connect-persist
./install.sh ds-hbase-2x
./install.sh last-command
./install.sh mlsql-bigdl
./install.sh mlsql-excel
./install.sh run-script
./install.sh save-then-load
./install.sh stream-persist
./install.sh table-repartition